### ISSUE TITLE
Error in Ubuntu 18.04

### ISSUE THREAD

**Issue by Toposku** [AaronJackson/vrn#148]
HI Aaron, there is some error I met when running the code. Do you know any solutions about this?

Scanning directory for data...	
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
/home/jk/usr/local/torch/install/bin/luajit: getrf : Lapack library not found in compile time
 at /tmp/luarocks_torch-scm-1-5412/torch7/lib/TH/generic/THLapack.c:140
stack traceback:
	[C]: at 0x7f5b7b39cc80
	[C]: in function 'inverse'
	./utils.lua:51: in function 'transform'
	./utils.lua:59: in function 'crop'
	main.lua:58: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55c231bec570
ls: cannot access '*.txt': No such file or directory
ls: cannot access '*.raw': No such file or directory

**Comment by AaronJackson** [comment]
/home/jk/usr/local/torch/install/bin/luajit: getrf : Lapack library not found in compile time

try reinstalling torch after installing the lapack devel packages.

**Comment by Toposku** [comment]
Hi Aaron, thanks for your reply. I reinstalled Torch and lapack pakage and it shows the command below:

Scanning directory for data...	
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
Cropped and scaled AFLW_image00046.jpg
Cropped and scaled AFLW_image00095.jpg
Cropped and scaled AFLW_image00190.jpg
Cropped and scaled AFLW_image00656.jpg
Cropped and scaled asj.jpg
Processed AFLW_image00190.
Processed AFLW_image00046.
Processed AFLW_image00095.
Processed asj.
Processed AFLW_image00656.
Traceback (most recent call last):
  File "../vis.py", line 20, in <module>
    t = vv.imshow(im)
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/backends/__init__.py", line 230, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk.
Traceback (most recent call last):
  File "../vis.py", line 20, in <module>
    t = vv.imshow(im)
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/backends/__init__.py", line 230, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk.
Traceback (most recent call last):
  File "../vis.py", line 20, in <module>
    t = vv.imshow(im)
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/backends/__init__.py", line 230, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk.
Traceback (most recent call last):
  File "../vis.py", line 20, in <module>
    t = vv.imshow(im)
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/backends/__init__.py", line 230, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk.
Traceback (most recent call last):
  File "../vis.py", line 20, in <module>
    t = vv.imshow(im)
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/home/jk/.local/lib/python2.7/site-packages/visvis/backends/__init__.py", line 230, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk.

**Comment by Toposku** [comment]
Does this mean that I need to install all of this? (PySide2, PyQt5, PySide, PyQt4, wxPython, GTK, or fltk).

**Comment by Toposku** [comment]
I tried using matlab and it run successfully after I installed the Image processing Toolbox. Could you please tell me how to use my own image? Do i just replace the images into the input_folder?

**Comment by AaronJackson** [comment]
Yeah put your images in the input folder and they should process. Glad you got it working.

**Comment by AaronJackson** [comment]
By the way - the matlab surface extraction function is better than what I could find in python anyway, so the quality should be better :-)

**Comment by Toposku** [comment]
Thanks for your help! I tried with my own image and it's working good.
