### ISSUE TITLE
Error importing "pyqt4" and "gtk" backend

### ISSUE THREAD

**Issue by DeqiangXiao** [AaronJackson/vrn#31]
Hi Aaron,
I executed "run.sh" on our linux server, the following errors display:

> Error importing pyqt4 backend: cannot import name QtOpenGL
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Error importing gtk backend: No module named gtkgl
Traceback (most recent call last):
  File "../vis.py", line 24, in <module>
    t = vv.imshow(im)
  File "/usr/local/lib/python2.7/dist-packages/visvis/functions/imshow.py", line 57, in imshow
    axes = vv.gca()
  File "/usr/local/lib/python2.7/dist-packages/visvis/functions/gca.py", line 19, in gca
    f = vv.gcf()
  File "/usr/local/lib/python2.7/dist-packages/visvis/functions/gcf.py", line 23, in gcf
    return vv.figure()
  File "/usr/local/lib/python2.7/dist-packages/visvis/functions/figure.py", line 23, in figure
    backends.use()
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/__init__.py", line 229, in use
    raise RuntimeError("None of the backends could be loaded. "+tmp)
RuntimeError: None of the backends could be loaded. Install PySide, PyQt4, wxPython, GTK, or fltk.

I checked this error on google, but still cannot understand what it is caused by.
Do you have any idea about it? Thanks in advance!

**Comment by AaronJackson** [comment]
Do as it says - install PyQt4. However, as you are connecting via a server there may not be any way to display it to you, and X11 forwarding may result in OpenGL issues.

**Comment by DeqiangXiao** [comment]
Hi Aaron,
I finally got through the code testing on our server after installing PyQt4, the results cannot be shown in the server as you pointed, while I can download the results on own pc and figured this issue out. Thank you very much!

**Comment by AaronJackson** [comment]
Glad you found a way to make it work. 

Enjoy!
