### ISSUE TITLE
It seems that I have some questions. 

### ISSUE THREAD

**Issue by zhoujianwen** [AaronJackson/vrn#65]
Hi, AaronJackson

I have configured the environment in accordance with the examples. It seems that I have some questions. I execute "rum.m" to produce data successfully, but it does not output 3D face data, but only generates facial mark point location information.

Is the following screenshot the final effect?
![wx20180328-145509](https://user-images.githubusercontent.com/13137730/38019883-64597b90-32ab-11e8-9252-2dc144b1ccc6.png)

When I execute "run.sh", I will prompt the following errors during the running of the program, but the data can be generated after the program is finished, which is the same as the run.m execution result.
```shell
[root@localhost vrn]# ./run.sh
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5Scanning directory for data...
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
Cropped and scaled AFLW_image00046.jpg
Cropped and scaled AFLW_image00095.jpg
Cropped and scaled AFLW_image00190.jpg
Cropped and scaled AFLW_image00656.jpg
Cropped and scaled asj.jpg
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5Processed AFLW_image00046.
Processed AFLW_image00095.
Processed AFLW_image00190.
Processed AFLW_image00656.
Processed asj.
····················
········································
················································································
File "/usr/lib/python2.7/site-packages/imageio/plugins/pillow.py", line 50, in _init_pillow
Raise ImportError ('Imageio Pillow requires "
ImportError: Imageio Pillow requires Pillow, not PIL!
```

I am now going to remove PIL and hope to be successful.

**Comment by AaronJackson** [comment]
You probably have something wrong with your OpenGL setup. Try starting MATLAB with softwareopengl.

```
matlab -softwareopengl
```

**Comment by AaronJackson** [comment]
Did this help?

**Comment by zhoujianwen** [comment]
I've solved the problem.
```
ImportError: Imageio Pillow requires Pillow, not PIL!
```

But the new problem has come up again.

```shell
[root@localhost vrn]# ./run.sh
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5Scanning directory for data...	
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
Cropped and scaled AFLW_image00046.jpg
Cropped and scaled AFLW_image00095.jpg
Cropped and scaled AFLW_image00190.jpg
Cropped and scaled AFLW_image00656.jpg
Cropped and scaled asj.jpg
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5Processed AFLW_image00046.
Processed AFLW_image00095.
Processed AFLW_image00190.
Processed AFLW_image00656.
Processed asj.
Traceback (most recent call last):
  File "../vis.py", line 28, in <module>
    volRGB = np.stack(((vol > 1) * im[:,:,0],
AttributeError: 'module' object has no attribute 'stack'
Traceback (most recent call last):
  File "../vis.py", line 28, in <module>
    volRGB = np.stack(((vol > 1) * im[:,:,0],
AttributeError: 'module' object has no attribute 'stack'
Traceback (most recent call last):
  File "../vis.py", line 28, in <module>
    volRGB = np.stack(((vol > 1) * im[:,:,0],
AttributeError: 'module' object has no attribute 'stack'
Traceback (most recent call last):
  File "../vis.py", line 28, in <module>
    volRGB = np.stack(((vol > 1) * im[:,:,0],
AttributeError: 'module' object has no attribute 'stack'
Traceback (most recent call last):
  File "../vis.py", line 28, in <module>
    volRGB = np.stack(((vol > 1) * im[:,:,0],
AttributeError: 'module' object has no attribute 'stack'
```
---------------------------------------------------------
```shell
[root@localhost bin]# ./matlab -softwareopengl
MATLAB is selecting SOFTWARE OPENGL rendering.
```
As the result of the last run, it does not output 3D face data, and only generates facial mark point location information.

**Comment by AaronJackson** [comment]
Well, in MATLAB it *is* working, but a problem with MATLAB is resulting in the actual 3D not showing. Have you removed any lines from `rendervol.m`? Such as enabling lighting...

**Comment by AaronJackson** [comment]
Do a `git diff` to check if you have changed anything.

**Comment by vanpersie32** [comment]
@zhoujianwen hi, I have the same problem with you. I run the code of matlab version with opengl start, but only the code only generates facial mark point location information
